language: csharp
solution: IPTables.Net.sln
mono:
  - latest
git:
  depth: 300
sudo: true
install:
  - sudo apt-get -qq install nunit-console iptables-dev realpath
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  
script:
  - cd ipthelper
  - ADDITIONAL_CFLAGS="-DOLD_IPTABLES" sudo -E bash install.sh
  - cd ..
  - bash travis-ci/autoversion.sh IPTables.Net
  - bash travis-ci/autoversion.sh IPTables.Net.Tests
  - bash travis-ci/autoversion.sh IPTables.Net.TestFramework
  - export EnableNuGetPackageRestore=false
  - mozroots --import --sync
  - travis_retry mono .nuget/NuGet.exe restore IPTables.Net.sln
  - xbuild /p:Configuration=Release IPTables.Net.sln
  - xbuild /p:Configuration=Debug IPTables.Net.sln
  - iptables -V
  - sudo nunit-console -framework=4.0 ./IPTables.Net.Tests/bin/Debug/IPTables.Net.Tests.dll -exclude Integration,NotWorkingOnMono
  - travis_retry bash travis-ci/nuget-upload.sh IPTables.Net