language: c
 
install:
  - sudo apt-get -qq install mono-devel mono-gmcs nunit-console
 
script:
  - export EnableNuGetPackageRestore=true
  - mozroots --import --sync
  - xbuild CI.proj
  - nunit-console ./IPTables.Net.Tests/bin/Debug/IPTables.Net.Tests.dll -exclude Integration,NotWorkingOnMono
