language: c
 
install:
  - sudo apt-get -qq install mono-devel mono-gmcs nunit-console
 
script:
  - cd ipthelper
  - make Release
  - make Debug
  - cd ..
  - export EnableNuGetPackageRestore=true
  - mozroots --import --sync
  - xbuild CI.proj
  - cp ./ipthelper/Debug/libipthelper.so ./IPTables.Net.Tests/bin/Debug/libipthelper.so
  - cp ./ipthelper/Release/libipthelper.so ./IPTables.Net.Tests/bin/Release/libipthelper.so
  - nunit-console ./IPTables.Net.Tests/bin/Debug/IPTables.Net.Tests.dll -exclude Integration,NotWorkingOnMono
