language: c

git:
  depth: 300

install:
  - sudo add-apt-repository ppa:directhex/ppa -y
  - sudo apt-get update
  - sudo apt-get -qq install mono-devel mono-gmcs mono-utils mono-complete libmono-system2.0-cil libmono-corlib2.0-cil mono-2.0-gac nunit-console iptables-dev
  
script:
  - cd ipthelper
  - ADDITIONAL_CFLAGS="-DOLD_IPTABLES" sudo -E bash install.sh
  - cd ..
  - bash travis-ci/autoversion.sh
  - export EnableNuGetPackageRestore=true
  - mozroots --import --sync
  - xbuild CI.proj
  - iptables -V
  - sudo nunit-console -framework=4.0 ./IPTables.Net.Tests/bin/Debug/IPTables.Net.Tests.dll -exclude Integration,NotWorkingOnMono
  - bash travis-ci/nuget-upload.sh