language: csharp
solution: IPTables.Net.sln
mono:
  - latest
git:
  depth: 300
sudo: true
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - nunit-console 
    - iptables-dev
    - realpath
    - libnl-3-dev
    - libnl-3-200
    - libnetfilter-conntrack3
    - libnfnetlink-dev
    - libnfnetlink0
install:
  - sudo modprobe ip_conntrack
script:
  - cd ipthelper
  - CXX="g++-4.8" ADDITIONAL_CFLAGS="-DOLD_IPTABLES" sudo -E bash install.sh
  - cd ..
  - bash travis-ci/autoversion.sh IPTables.Net
  - bash travis-ci/autoversion.sh IPTables.Net.Tests
  - bash travis-ci/autoversion.sh IPTables.Net.TestFramework
  - export EnableNuGetPackageRestore=false
  - mozroots --import --sync
  - travis_retry mono .nuget/NuGet.exe restore IPTables.Net.sln
  - xbuild /p:Configuration=Release IPTables.Net.sln
  - xbuild /p:Configuration=Debug IPTables.Net.sln
  - iptables -V
  - sudo nunit-console -framework=4.0 ./IPTables.Net.Tests/bin/Debug/IPTables.Net.Tests.dll -exclude Integration,NotWorkingOnMono
  - travis_retry bash travis-ci/nuget-upload.sh IPTables.Net