version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1-buster
      
    working_directory: ~/repo

    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install -y git
      - run:
          name: Build
          command: dotnet build
      - run:
          name: NUnit Tests
          command: SKIP_SYSTEM_TESTS=1 dotnet test IPTables.Net.Tests
      - persist_to_workspace:
          root: /root/
          paths: 
           - repo
  upload:
    requires:
     - build
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1-buster
      
    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: /root/repo
      - run:
          name: NuGet upload
          command: |
            ls -las /root/repo
            bash nuget-upload.sh IPTables.Net