version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
      
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: NUnit Tests
          command: dotnet test IPTables.Net.Tests