version: 2

workflows:
  version: 2
  build_test_upload:
    jobs:
      - build
      - machine_test
      - upload

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1-buster
      
    working_directory: /root/repo

    steps:
      - checkout
      - run:
          name: Build
          command: dotnet build
      - run:
          name: NUnit Tests
          command: SKIP_SYSTEM_TESTS=1 dotnet test IPTables.Net.Tests
  machine_test:
    machine:
      image: ubuntu-1604
    steps:
      - checkout
      - run: |
          wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb

          sudo apt-get update; \
            sudo apt-get install -y apt-transport-https && \
            sudo apt-get update && \
            sudo apt-get install -y dotnet-sdk-3.1


  upload:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1-buster
      
    requires:
     - build
     - machine_test
      
    working_directory: /root/repo

    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install -y git
      - run:
          name: NuGet upload
          command: |
            ls -las /root/repo
            bash nuget-upload.sh IPTables.Net