version: 2

workflows:
  version: 2
  build_test_upload:
    jobs:
      - build
      - upload

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1-buster
      
    working_directory: /root/repo

    steps:
      - checkout
      - run:
          name: Build
          command: dotnet build
      - run:
          name: NUnit Tests
          command: SKIP_SYSTEM_TESTS=1 dotnet test IPTables.Net.Tests
      - persist_to_workspace:
          root: /root/repo
          paths: 
           - .
  machine_test:
    machine:
      image: ubuntu-1604
    steps:
      - attach_workspace:
          at: /root/repo


  upload:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1-buster
      
    requires:
     - build
      
    working_directory: /root/repo

    steps:
      - attach_workspace:
          at: /root/repo
      - run: |
          apt-get update
          apt-get install -y git
      - run:
          name: NuGet upload
          command: |
            ls -las /root/repo
            bash nuget-upload.sh IPTables.Net