version: 2

workflows:
  version: 2
  build_test_upload:
    jobs:
      - build
      - machine_test
      - upload:      
          requires:
          - build
          - machine_test

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1-buster
      
    working_directory: /root/repo

    steps:
      - checkout
      - run:
          name: Build
          command: dotnet build
      - run:
          name: NUnit Tests
          command: SKIP_SYSTEM_TESTS=1 dotnet test IPTables.Net.Tests
  machine_test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: |
          wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb

          sudo apt-get update; \
            sudo apt-get install -y apt-transport-https && \
            sudo apt-get update && \
            sudo apt-get install -y dotnet-sdk-3.1 build-essential iptables-dev libnl-3-dev libnl-3-200 libnetfilter-conntrack3 libnfnetlink-dev libnfnetlink0 libpcap0.8 libpcap0.8-dev
      - run: |
          cd ipthelper
          CONFIG="Release" sudo -E bash install.sh
          CONFIG="Debug" sudo -E bash install.sh
          ldconfig
      - run: |
          dotnet test

  upload:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1-buster
      
    working_directory: /root/repo

    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install -y git
      - run:
          name: NuGet upload
          command: |
            bash nuget-upload.sh IPTables.Net